name: Publish Package

on:
  release:
    types: [ created, edited ]
  workflow_dispatch:

jobs:
  build:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        registry-url: https://registry.npmjs.org
      env:
        BUN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: bun install
    - run: bun publish --access public
